Meilenstein_4/Websites/Paket_4/Controllers/BenutzerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using System.Web.Routing;
using DBForum.Models;
using DBForum.Models.PraktikumTableAdapters;

namespace DBForum.Controllers
{
    public class BenutzerController : Controller
    {

        // GET: /Benutzer/
        public ActionResult Index()
        {
            return RedirectToAction("List");
        }

        // GET: /Benutzer/List
        public ActionResult List()
        {
            return View(Benutzer.GetBenutzer());
        }



        // GET: /Benutzer/Statistik
        public ActionResult Stats(string c)
        {
            if (string.IsNullOrEmpty(c))
                c = "";
            ViewBag.ReqChar = c.ToLower();

            var adapter = new BenutzerrollenTableAdapter();

            Praktikum.BenutzerrollenDataTable result;
            if (string.IsNullOrEmpty(c))
                result = adapter.GetData();
            else
                result = adapter.GetDataByFirstChar(c);

            return View(result);
        }


        // GET: /Benutzer/Statistik
        public ActionResult StatsChart(string c)
        {
            if (string.IsNullOrEmpty(c))
                c = "";
            ViewBag.ReqChar = c.ToLower();

            var adapter = new BenutzerrollenTableAdapter();
            Praktikum.BenutzerrollenDataTable result;
            if (string.IsNullOrEmpty(c))
                result = adapter.GetData();
            else
                result = adapter.GetDataByFirstChar(c);

            var amounts = new Dictionary<string, int>();
            foreach (var user in result)
            {
                if (!amounts.ContainsKey(user.Rolle))
                    amounts[user.Rolle] = 1;
                else
                    amounts[user.Rolle]++;
            }

            var chart = new Chart(width: 600, height: 400).AddSeries(
                chartType: "pie",
                legend: "Verteilung der Benutzerrollen",
                xValue: amounts.Keys,
                yValues: amounts.Values).Write("png");
            return null;
        }


        // GET: /Benutzer/Summary
        public ActionResult Summary(string user)
        {
            return View(Benutzer.GetBenutzerByNickname(user));
        }

        // GET: /Benutzer/Add
        public ActionResult Add()
        {
            return View(new Student());
        }

        // POST: /Benutzer/Add
        [HttpPost]
        public ActionResult Add(FormCollection fc)
        {
           
            var student = new Student();
            student.Nickname = fc["Nickname"];
            student.Vorname = fc["Vorname"];
            student.Nachname = fc["Nachname"];
            student.Email = fc["Email"];
            student.Passwort = fc["Passwort"];

            int tmp = 0;
            Int32.TryParse(fc["MatrikelNummer"], out tmp);
            student.MatrikelNummer = tmp;

            DateTime tmpdate;
            DateTime.TryParse(fc["EinschreibeDatum"], out tmpdate);
            student.EinschreibeDatum = tmpdate;

            ViewBag.ErrorMessages = null;
            var errorMessages = new List<string>();
            var valid = student.Validate(ref errorMessages);
            if (fc["Passwort"].Length == 0 || fc["Passwort"] != fc["PasswortWdh"])
            {
                valid = false;
                errorMessages.Add("Das Passwort ist ungültig oder es stimmt nicht mit der Wiederholung überein.");
            }

            if (valid)
            {
                student.Save();
                FlashMessage.AddFlashMessage( "Der Benutzer wurde erfolgreich hinzugefügt.", FlashMessage.MessageType.Success);
                return RedirectToAction("List");
            }
            else
                ViewBag.ErrorMessages = errorMessages;

            return View(student);
        }




    }
}

Meilenstein_4/Websites/Paket_4/Controllers/ModuleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DBForum.Models;

namespace DBForum.Controllers
{
    public class ModuleController : Controller
    {
        
        // GET: /Module/
        public ActionResult Index()
        {
            BreadCrumb.ClearBreadCrumbs();
            return RedirectToAction("List");
        }

        // GET: /Module/List
        public ActionResult List()
        {
            return View(Modul.GetModule());
        }

    }
}

Meilenstein_4/Websites/Paket_4/Views/Module/List.cshtml
@using DBForum.Models
@model List<DBForum.Models.Modul>
@{    
    ViewBag.Title = "Module";
    ViewBag.SubTitle = "Übersicht";

    BreadCrumb.AddBreadCrumb(new BreadCrumb{ Action = "Index", Controller = "Home", Title = "Home"});
    BreadCrumb.AddBreadCrumb(new BreadCrumb {Active = true, Title = "Module" });

}


<div class="panel panel-default">
    <div class="panel-heading">Module
        <span class="badge pull-right">@Model.Count</span>
        </div>
    <table class="table table-hover">
        <thead>  
            <tr>  
                <th  style="width: 15%">Fachnummer</th>  
                <th style="width: 55%">Bezeichnung</th>  
                <th style="width: 30%">Verantwortlicher</th>
              
            </tr>  
        </thead>  
        <tbody>
       
        @foreach (var modul in Model) {
            <tr>
                <td>@modul.FachNummer</td>
                <td>@modul.Bezeichnung</td>
                <td><a href="@Url.Action("Summary", "Benutzer", new { user = modul.Verantwortlicher} )">@modul.VerantwortlicherName</a></td>

            </tr>
        }
        </tbody>  
    </table>
</div>